language: ruby
cache: bundler
rvm:
  - 2.3.3 # git.ruby-lang.org uses ruby 2.3.3 by default
branches:
  only:
    - master
before_install:
  - git clone --depth=3 https://github.com/ruby/ruby

  # Install dummy `sendmail` for testing commit-email.rb
  - |-
    echo "#!/usr/bin/env ruby
          p ARGV
          puts STDIN.read" > ./sendmail
    chmod +x ./sendmail
    sudo mv ./sendmail /usr/sbin/sendmail

script:
  - |-
    cd ./ruby &&
    ../bin/commit-email.rb ./ cvs-admin@ruby-lang.org \
      $(git rev-parse HEAD^) $(git rev-parse HEAD) refs/heads/master \
      --viewer-uri "https://github.com/ruby/ruby/commit/" \
      --error-to cvs-admin@ruby-lang.org
  - bundle exec rake test
