language: ruby
rvm:
  - 2.1 # git.ruby-lang.org is debian 8 (jessie), ruby 2.1.5p273
branches:
  only:
    - master
before_install:
  - git clone --depth=3 https://github.com/ruby/ruby

  # Install dummy `sendmail` for testing commit-email.rb
  - |-
    echo "#!/usr/bin/env ruby
          p ARGV
          puts STDIN.read" > ./sendmail
    chmod +x ./sendmail
    sudo mv ./sendmail /usr/sbin/sendmail

script:
  - |-
    cd ./ruby &&
    ../bin/commit-email.rb ./ cvs-admin@ruby-lang.org \
      $(git rev-parse HEAD^) $(git rev-parse HEAD) refs/heads/trunk \
      --viewer-uri "https://github.com/ruby/ruby/commit/" \
      --error-to cvs-admin@ruby-lang.org
